In [3]:
import tensorflow as tf
import numpy as np

In [50]:
def dictionaryGen(D):
    
    """ Generate and return 
        - D integers on the x axis evenly distributed around 0 (??? w/ abs value \leq 100 ???)
        - The step size Δx """

    d_pos = np.linspace(0, 100, num= int(D/2)+1, endpoint=False, retstep=True, dtype=np.float32)
    d_neg = (-1*d_pos[0][1:]) # get the negative dictionary points  
    return (d_pos[1], np.concatenate((np.sort(d_neg), d_pos[0][1:]), axis=None))


def gaussianKer1D(s, d_i, b_width):

    """ Compute 1D Gaussian kernel as defined in arXiv:1707.04035 """
    
    x = np.power((s - d_i), 2)
    return np.exp(-b_width*x)

In [51]:
print(tf.reduce_sum(gaussianKer1D(np.array([13.53]), np.array([20, -20]), 0.32)))
gaussianKer1D(np.array([13.53]), np.array([20, -20]), 0.32)

tf.Tensor(1.5219958883602659e-06, shape=(), dtype=float64)


array([1.52199589e-006, 5.71087128e-157])

In [52]:
step, d = dictionaryGen(50)
tf.constant(d)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-96.15385  , -92.30769  , -88.46154  , -84.61539  , -80.76923  ,
       -76.92308  , -73.07692  , -69.23077  , -65.38461  , -61.53846  ,
       -57.692307 , -53.846153 , -50.       , -46.153847 , -42.307693 ,
       -38.46154  , -34.615383 , -30.76923  , -26.923077 , -23.076923 ,
       -19.23077  , -15.384615 , -11.538462 ,  -7.6923075,  -3.8461537,
         3.8461537,   7.6923075,  11.538462 ,  15.384615 ,  19.23077  ,
        23.076923 ,  26.923077 ,  30.76923  ,  34.615383 ,  38.46154  ,
        42.307693 ,  46.153847 ,  50.       ,  53.846153 ,  57.692307 ,
        61.53846  ,  65.38461  ,  69.23077  ,  73.07692  ,  76.92308  ,
        80.76923  ,  84.61539  ,  88.46154  ,  92.30769  ,  96.15385  ],
      dtype=float32)>

In [128]:
from tensorflow.keras.layers import Layer

class Kaf(Layer):

    def __init__(self, D, **kwargs):

        super(Kaf, self).__init__()
        
        # Initialize constants
        self.D = D
        step, dict = dictionaryGen(D)
        self.d = tf.constant(dict)
        self.k_bandw = 1/(6*(np.power(step,2)))
        

    def build(self, input_shape):
        
        print(input_shape)
        # Mixing coefficients sampled from a normal dist
        #self.a = self.add_weight(shape=(input_shape[-1], self.D), 
        #                         initializer= 'random_normal',
        #                         trainable=True)

    def call(self, inputs):
        
        #print(self.a)
        #y = []
        #for i in range (0, inputs.shape[0]): # for each input unit
        #    y_i = []
        #    for j in range (0, tf.size(inputs[i])): # apply the activation function element-wise for each neuron
        #        y_i.append(tf.reduce_sum(self.a[j] * gaussianKer1D(inputs[i][j], self.d, self.k_bandw)))
        #    y.append(y_i)                
        #
        #y = tf.stack(y) # convert back to a tensor
        #print(y)
        #print(x)
        #return y 

SyntaxError: invalid syntax (<ipython-input-128-2328c1f9dd38>, line 5)

In [126]:
x = tf.random.uniform(shape = (4,), minval=-20, maxval=40, dtype=tf.float32)

print(tf.size(x[1]))

kaf = Kaf(20)
#
kaf(x)

tf.Tensor(1, shape=(), dtype=int32)
<tf.Variable 'kaf_55/Variable:0' shape=(4, 20) dtype=float32, numpy=
array([[ 0.01689988, -0.00806069,  0.10421381, -0.02961117, -0.00608115,
         0.0317506 , -0.0165346 , -0.02313367, -0.02285305,  0.06128451,
        -0.09191964,  0.01569757,  0.03711598, -0.08986508, -0.03955432,
         0.02846296,  0.0047694 , -0.00418693, -0.023147  ,  0.04940532],
       [ 0.0067636 ,  0.05084299, -0.06556311, -0.0810833 ,  0.00482153,
        -0.06822176,  0.01916341, -0.02562395, -0.01808073,  0.07672176,
         0.10020856, -0.02022963,  0.05048233, -0.02456616, -0.02723691,
         0.05990466,  0.06356709, -0.00389831, -0.01109615, -0.06248103],
       [ 0.02697686, -0.04271223,  0.01108009, -0.0538299 , -0.04903933,
         0.00467208,  0.08219342,  0.04768388,  0.0753132 ,  0.01165142,
        -0.02349227,  0.0356625 ,  0.01038878, -0.00186831,  0.01987037,
        -0.03740392, -0.09807961, -0.01099442, -0.10152217, -0.03915821],
       [ 0.02572